services:
  - type: web
    name: fastapi-service
    env: docker
    repo: https://github.com/RoshanDevassy/SolarPanel_DeepLearning.git
    branch: main
    rootDir: backend
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
    buildCommand: "pip install -r api/requirements.txt"
    startCommand: "python api/models/startup.py && uvicorn api.main:app --host 0.0.0.0 --port 10000"
